name: 'Markdown Linter'
description: 'Lint markdown files using write-good'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npm install -g write-good
      shell: bash
    - run: |
        echo "Checking markdown files..."
        find . -name "*.md" -exec write-good {} \;
      shell: bash
